### ISSUE TITLE
Oslc Xml Provider always kicks in for application/xml

### ISSUE THREAD

**Issue by benjaminr-ps** [eclipse/lyo#356] opened 2023-06-09 12:48 UTC
The Olsc Xml Provider is not usable in a mixed setup, with simple JAXB Provider, since it is now always tried to read as RDF/XML.

Can you please fix this issue? 
We try to upgrade from previous version of Eclipse Lyo.

I can't upgrade to 5, since this is already build with Java 11.

https://github.com/eclipse/lyo/blob/bdac27f62e1737687868dd0942ad4bd7da0f182b/core/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/OslcRdfXmlProvider.java#L232

**Comment by berezovskyi** [comment] 2023-06-09 13:19
Hello Benjamin,

Are you asking us to apply this fix? https://github.com/eclipse/lyo/pull/228

Also, please specify which version do you need fixed? From the link you gave, it looks like 4.1.0.

Regarding the fix itself, we need to be quite careful, because this is the place where any change could be breaking if someone relied on it (cf. https://www.hyrumslaw.com/). **I think that the actual problem is not in the `isReadable` method but on the `JenaProvidersRegistry`.** There, classes that bind to `application/xml` (not `application/rdf+xml`) are added:

https://github.com/eclipse/lyo/blob/master/core/oslc4j-jena-provider/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/JenaProvidersRegistry.java#LL29C1-L31C40

You should be able to work around it in your application by registering your providers like this:

```java
        RESOURCE_CLASSES.addAll(JenaProvidersRegistry.getProviders());
        RESOURCE_CLASSES.remove(OslcXmlArrayProvider.class);
        RESOURCE_CLASSES.remove(OslcXmlCollectionProvider.class);
        RESOURCE_CLASSES.remove(OslcXmlProvider.class);
```

PS. We already made changes/tests to the isReadable/isWritable methods in these two PRs:

1. https://github.com/eclipse/lyo/pull/286
2. https://github.com/eclipse/lyo/pull/288

**Comment by berezovskyi** [comment] 2023-06-09 13:21
@jadelkhoury I would also like to remove these providers either from `JenaProvidersRegistry.getProviders()` in Lyo 6 or add a `JenaProvidersRegistry.getProvidersModern()` sans these bad providers or have Lyo Designer generate the code either to call `JenaProvidersRegistry.getProvidersModern()` or apply the workaround I listed above.

**Comment by berezovskyi** [comment] 2023-06-09 13:23
We should also deprecate `OslcXmlProvider`, `OslcXmlArrayProvider`, `OslcXmlCollectionProvider` and encourage RDF/XML only to be parsed by `OslcRdfXmlProvider` and friends.

**Comment by Jad-el-khoury** [comment] 2023-06-12 11:07
Hi @benjaminr-ps 

Somewhere in your code (I guess an Application class that extends javax.ws.rs.core.Application), you are calling  `JenaProvidersRegistry.getProviders()` which actually returns **all** OSLC providers, including the ones that you do not desire to register.

So instead of calling `JenaProvidersRegistry.getProviders()`, why not simply pick the providers you want to add? See the implementation of that method to get a more exact list of providers to pick from.
Alternatively, as suggested by @berezovskyi follow the call, but some calls to remove the undesired ones.

I believe this would be a more stable solution. Calling `JenaProvidersRegistry.getProviders()`  is simply a convenience method to register all providers, but this is not your case, so why register them in the first place?

**Comment by Jad-el-khoury** [comment] 2023-06-12 11:11
> @jadelkhoury I would also like to remove these providers either from `JenaProvidersRegistry.getProviders()` in Lyo 6 or add a `JenaProvidersRegistry.getProvidersModern()` sans these bad providers or have Lyo Designer generate the code either to call `JenaProvidersRegistry.getProvidersModern()` or apply the workaround I listed above.

@berezovskyi are there "bad" providers, or are some simply not desired in certain scenarios.
Ideally, the method would have been called the more accurate `getAllProviders` instead. 
In LyoDesigner, we can simply add a user code block that explains the setup, plus gives the user the option to remove certain ones.

**Comment by berezovskyi** [comment] 2023-06-12 11:56
> Currently, I am not interested in any future versions of Eclipse Lyo.

@benjaminr-ps It's fine, we are only asking you to clearly state the version you are using right now.

> Returning true is the only problem, which seems to be changed from version 2.4 to 4.x, which is a breaking change already. I would even go further and say it's a bug, since I do not see any evidence doing so.

The reason to reduce the checks was to allow instances of different resources to be de/serialized, see https://github.com/eclipse/lyo.core/issues/21. Setting it to `true` was a mistake, but not because of the issue you described but because non-collection providers could sometimes trigger on collections. And given that's a breaking change, that's exactly why it was postponed from being released in 2.4.0 and instead delivered in 4.0.0.

> Now, I have circumvented the situation, defining my own provider which inherits the OslcRdfXmlProvider and checks with old behaviour.

Could you please confirm that the JAXB Provider is supposed to read `application/xml` and the `application/xml` gets passed to `OslcRdfXmlProvider` that is configured with `@Consumes(value="application/rdf+xml")`? You can do this by checking the value of the `mediaType` in `isReadable`. 

To be clear, this should never happen. We've had a small number of such reports over the years but I was never able to reproduce with Jersey to trigger a provider on a MIME type it didn't declare. Please confirm you are using Jersey (<= 2.29.1 if you are on Lyo 4.x, iirc), package as WAR and run it using Tomcat or Jetty in a non-embedded more? These are the environments we regularly test. And please confirm Jersey is calling `OslcRdfXmlProvider.isReadable` when you POST some `application/xml` content, not `OslcXmlProvider.isReadable`.

I tested `RESOURCE_CLASSES.remove(OslcXmlProvider.class)` on the https://github.com/oslc-op/refimpl/tree/21c41f22e02c4fe6ec23ae30ecda428fc1afbca1 (using Lyo 4.1.0.RC) and it stopped the API from accepting `application/xml` perfectly. If you can modify the reference implementation at that version to trigger the bug, we can discuss a bugfix release. See my test under https://github.com/oslc-op/refimpl/commit/91b92c682aede6cb15fcb6a534115a4fe36f158b

PS:

> I can't upgrade to 5, since this is already build with Java 11.

We are trying to stay as low as possible with the JDK requirement, we understand the needs of integration library users. But our upstream dependencies are making our life hard, esp. Jena, which we can't replace. They already declared a plan to drop JDK 11 support shortly after JDK 21 is released in 2023-09 and only support JDK 17 and JDK 21. Spring framework, Jakarta EE, and many other projects seem to be following the "2 last LTS" policy as well.

Right now the policy of Lyo is to stay on the lowest JDK version possible, using oldest possible Jena versions without CVEs. But when a CVE is filed on Jena, we must upgrade due to security concerns and this sometimes brings a JDK dependency increase.

This is how things will remain to be unless we get enough financial support to keep forks of older Jena versions and backport CVE patches to them.

**Comment by benjaminr-ps** [comment] 2023-06-13 09:27
Thanks for your detailed thoughts.

My current setup looks as follows:
- Jersey 2.37
- Lyo 4.1.0

I noticed, that OslcRdfXmlProvider.isReadable is getting called, since being defined first by Jersey, and JAXB is not called.

Not sure, if there is any response with content-type "application/xml", but actually having the content with RDF/XML, returned by our supported 3rd party tools (like IBM's ELM).

(unfortunately anything can be possible in real world ;))

**Comment by berezovskyi** [comment] 2023-06-18 14:03
@benjaminr-ps I will close the issue. Please reopen if you can reproduce your issue on top of my JAXB example: https://github.com/oslc-op/refimpl/commit/91b92c682aede6cb15fcb6a534115a4fe36f158b

**Closed by berezovskyi** 2023-06-18 14:03 UTC
Labels: Type: Bug, Priority: High, Component: Core, Status: To be deprecated
